version: '3.8'
services:
  app:
    build:
      context: .
    container_name: loja-pecas-app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: root
      DB_DATABASE: loja_pecas
      DB_PORT: 3307
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: loja-pecas-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: loja_pecas
    ports:
      - "3307:3306" # Alterando para 3307 na máquina host
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
